export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Users } from './Users'
export {default as CompleteProfile} from './CompleteProfile'
export {default as AddUser} from './AddUser'
export {default as EditUser} from './EditUser'